name: My First Workflow

on: [push, fork]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: welcome message
        run: echo "welcome my friend" >> welcome.txt

      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: welcome
          path: welcome.txt
      

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v8
        with:
          name: welcome
          path: welcome.txt

      - name: testing
        run: |
          grep -i welcome welcome.txt

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: deploy the code
        run: echo "deploying..."