name: My First Workflow

on: [push, fork]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: welcome message
        run: sleep 10

  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: testing
        run: |
          echo "testing..."
          sleep 10

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: deploy the code
        run: echo "deploying..."